#                                           __
# _ __   __ _ _ __ _   _   ___ ___  _ __  / _|
#| '_ \ / _` | '__| | | | / __/ _ \| '_ \| |_
#| |_) | (_| | |  | |_| || (_| (_) | | | |  _|
#| .__/ \__,_|_|   \__,_(_)___\___/|_| |_|_|
#|_|
#

# $PARU_CONF
# /etc/paru.conf
# ~/.config/paru/paru.conf
#
# See the paru.conf(5) manpage for options

#
# GENERAL OPTIONS
#
[options]
SkipReview
PgpFetch
Devel
Provides
DevelSuffixes = -git -cvs -svn -bzr -darcs -always
#BottomUp
RemoveMake
#SudoLoop
#UseAsk
#CombinedUpgrade
#CleanAfter
#UpgradeMenu
NewsOnUpgrade

#LocalRepo
#Chroot
#MovePkgs

#
# Binary OPTIONS
#
#[bin]
#FileManager = vifm
#MFlags = --skippgpcheck
#Sudo = /usr/bin/doas
