[Appearance]
color_scheme_path=/home/love/.config/qt5ct/colors/catppuccin-mocha.conf
custom_palette=true
icon_theme=Papirus-Dark
standard_dialogs=default
style=kvantum

[Fonts]
fixed="JetBrains Mono,11,-1,5,50,0,0,0,0,0"
general="Noto Sans,11,-1,5,50,0,0,0,0,0"
