source = ~/.config/hypr/theme.conf

general {
    hide_cursor = true
    grace = 2
}

background {
    monitor =
    path = ~/Pictures/wallpapers/dynamic
    blur_passes = 2
    blur_size = 4
}

shape {
    monitor =
    size = 460, 360
    color = rgba(00000066)
    rounding = 18
    border_size = 0
    border_color = $overlay0
    position = 0, 10
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%H:%M')"
    color = $text
    font_size = 72
    font_family = Sans
    position = 0, 110
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%A, %d %B')"
    color = $subtext0
    font_size = 20
    font_family = Sans
    position = 0, 48
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 280, 56
    outline_thickness = 2
    dots_size = 0.22
    dots_spacing = 0.22
    dots_center = true
    fade_on_empty = false
    font_color = $text
    inner_color = $surface0
    outer_color = $overlay0
    check_color = $blue
    fail_color = $red
    placeholder_text = Password...
    hide_input = false
    rounding = 14
    position = 0, -40
    halign = center
    valign = center
}

label {
    monitor =
    text = $USER
    color = $text
    font_size = 18
    font_family = Sans
    position = 0, -112
    halign = center
    valign = center
}
